let rawData=[...window.INITIAL_DATA];let charts={};
const monthOrder=['MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO','JANEIRO','FEVEREIRO'];
const $=id=>document.getElementById(id);const brl=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});const num=n=>n.toLocaleString('pt-BR');const pct=n=>(n*100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
function options(){const months=[...new Set(rawData.map(d=>d.mes))].sort((a,b)=>monthOrder.indexOf(a)-monthOrder.indexOf(b));const sellers=[...new Set(rawData.map(d=>d.vendedor))].sort();$('monthFilter').innerHTML='<option value="TODOS">Todos os meses</option>'+months.map(x=>`<option>${x}</option>`).join('');$('sellerFilter').innerHTML='<option value="TODOS">Todos os vendedores</option>'+sellers.map(x=>`<option>${x}</option>`).join('')}
function filtered(){let m=$('monthFilter').value,v=$('sellerFilter').value;return rawData.filter(d=>(m==='TODOS'||d.mes===m)&&(v==='TODOS'||d.vendedor===v))}
function aggregate(rows,key){const map={};rows.forEach(d=>{const k=d[key];map[k]??={label:k,orcamentos:0,vendas:0,faturamento:0};map[k].orcamentos+=d.orcamentos;map[k].vendas+=d.vendas;map[k].faturamento+=d.faturamento});return Object.values(map).map(x=>({...x,conversao:x.vendas/(x.vendas+x.orcamentos),ticket:x.faturamento/x.vendas}))}
function destroy(name){if(charts[name])charts[name].destroy()}
function baseChart(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:getComputedStyle(document.body).getPropertyValue('--muted'),boxWidth:10,usePointStyle:true}}},scales:{x:{ticks:{color:getComputedStyle(document.body).getPropertyValue('--muted')},grid:{display:false}},y:{ticks:{color:getComputedStyle(document.body).getPropertyValue('--muted')},grid:{color:getComputedStyle(document.body).getPropertyValue('--border')}}}}}
function render(){const rows=filtered();const total=rows.reduce((a,d)=>({orcamentos:a.orcamentos+d.orcamentos,vendas:a.vendas+d.vendas,faturamento:a.faturamento+d.faturamento}),{orcamentos:0,vendas:0,faturamento:0});total.conversao=total.vendas/(total.vendas+total.orcamentos)||0;total.ticket=total.faturamento/total.vendas||0;const sellers=aggregate(rows,'vendedor').sort((a,b)=>b.faturamento-a.faturamento);const months=aggregate(rows,'mes').sort((a,b)=>monthOrder.indexOf(a.label)-monthOrder.indexOf(b.label));
$('kpiRevenue').textContent=brl(total.faturamento);$('kpiConversion').textContent=pct(total.conversao);$('kpiSales').textContent=num(total.vendas);$('kpiQuotes').textContent=num(total.orcamentos);$('kpiTicket').textContent='Ticket médio '+brl(total.ticket);$('kpiLeader').textContent=sellers[0]?.label||'—';$('kpiLeaderValue').textContent=sellers[0]?brl(sellers[0].faturamento):'—';$('scoreValue').textContent=pct(total.conversao);
const convLeader=[...sellers].sort((a,b)=>b.conversao-a.conversao)[0];$('insightTitle').textContent=convLeader?`${convLeader.label} lidera em eficiência comercial`:'Sem dados';$('insightText').textContent=convLeader?`Conversão de ${pct(convLeader.conversao)} no período filtrado. ${sellers[0].label} lidera o faturamento com ${brl(sellers[0].faturamento)}.`:'Ajuste os filtros ou importe uma planilha válida.';
chartsRender(months,sellers,total);tableRender(rows);funnelRender(total);}
function chartsRender(months,sellers,total){destroy('revenue');charts.revenue=new Chart($('revenueChart'),{type:'line',data:{labels:months.map(x=>x.label),datasets:[{label:'Faturamento',data:months.map(x=>x.faturamento),borderColor:'#246bfd',backgroundColor:'rgba(36,107,253,.12)',fill:true,tension:.35,pointRadius:4}]},options:{...baseChart(),scales:{...baseChart().scales,y:{...baseChart().scales.y,ticks:{color:'#6e7890',callback:v=>'R$ '+(v/1000).toFixed(0)+' mil'}}}}});
destroy('conversion');charts.conversion=new Chart($('conversionChart'),{type:'bar',data:{labels:sellers.map(x=>x.label),datasets:[{label:'Conversão',data:sellers.map(x=>x.conversao*100),backgroundColor:['#246bfd','#7a4af6','#16a36a','#f1a22b']}]},options:{...baseChart(),plugins:{legend:{display:false}},scales:{...baseChart().scales,y:{...baseChart().scales.y,beginAtZero:true,max:100,ticks:{color:'#6e7890',callback:v=>v+'%'}}}}});
destroy('ranking');charts.ranking=new Chart($('rankingChart'),{type:'doughnut',data:{labels:sellers.map(x=>x.label),datasets:[{data:sellers.map(x=>x.faturamento),backgroundColor:['#246bfd','#7a4af6','#16a36a','#f1a22b','#09a8c4'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'bottom',labels:{color:getComputedStyle(document.body).getPropertyValue('--muted'),usePointStyle:true}}}}});
destroy('volume');charts.volume=new Chart($('volumeChart'),{type:'bar',data:{labels:sellers.map(x=>x.label),datasets:[{label:'Orçamentos',data:sellers.map(x=>x.orcamentos),backgroundColor:'#a8b2c7'},{label:'Vendas',data:sellers.map(x=>x.vendas),backgroundColor:'#246bfd'}]},options:baseChart()});}
function funnelRender(t){const opp=t.orcamentos+t.vendas;const levels=[['Oportunidades',opp,'100%','#246bfd'],['Vendas',t.vendas,pct(t.vendas/opp||0),'#4d84f7'],['Faturamento',brl(t.faturamento),'Ticket '+brl(t.ticket),'#16a36a']];$('funnel').innerHTML=levels.map((x,i)=>`<div class="funnel-row" style="width:${100-i*15}%;background:${x[3]}"><span>${x[0]}</span><span>${typeof x[1]==='number'?num(x[1]):x[1]} <small>${x[2]}</small></span></div>`).join('')}
function tableRender(rows){const q=$('searchInput').value.toLowerCase();$('dataBody').innerHTML=rows.filter(d=>(d.vendedor+' '+d.mes).toLowerCase().includes(q)).map(d=>`<tr><td><strong>${d.vendedor}</strong></td><td>${d.mes}</td><td>${num(d.orcamentos)}</td><td>${num(d.vendas)}</td><td><span class="badge">${pct(d.conversao)}</span></td><td>${brl(d.faturamento)}</td><td>${brl(d.faturamento/d.vendas)}</td></tr>`).join('')}
function parseExcel(file){const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],grid=XLSX.utils.sheet_to_json(ws,{header:1,raw:true});const out=[];for(let r=0;r<grid.length;r++){const month=String(grid[r]?.[0]||'').trim().toUpperCase();if(!month)continue;for(let c=1;c<grid[r].length;c+=2){const seller=String(grid[r]?.[c]||'').trim();if(!seller)continue;const o=Number(grid[r+1]?.[c+1]),v=Number(grid[r+2]?.[c+1]),f=Number(grid[r+4]?.[c+1]);if(Number.isFinite(o)&&Number.isFinite(v)&&Number.isFinite(f))out.push({mes:month,vendedor:seller[0].toUpperCase()+seller.slice(1).toLowerCase(),orcamentos:o,vendas:v,faturamento:f,conversao:v/(o+v)});}}if(out.length){rawData=out;options();render();alert('Planilha importada com sucesso.')}else alert('Não foi possível reconhecer o formato da planilha.');};reader.readAsArrayBuffer(file)}
function exportCSV(){const rows=filtered(),head='Mês;Vendedor;Orçamentos;Vendas;Conversão;Faturamento\n',body=rows.map(d=>[d.mes,d.vendedor,d.orcamentos,d.vendas,(d.conversao*100).toFixed(2),d.faturamento.toFixed(2)].join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+head+body],{type:'text/csv'}));a.download='dashboard_comercial.csv';a.click()}
$('monthFilter').onchange=render;$('sellerFilter').onchange=render;$('searchInput').oninput=()=>tableRender(filtered());$('resetBtn').onclick=()=>{$('monthFilter').value='TODOS';$('sellerFilter').value='TODOS';$('searchInput').value='';render()};$('printBtn').onclick=()=>print();$('csvBtn').onclick=exportCSV;$('excelInput').onchange=e=>e.target.files[0]&&parseExcel(e.target.files[0]);$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');render()};options();render();
