'use strict';
let rawData=[...window.INITIAL_DATA],charts={};
const monthsOrder=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];
const $=id=>document.getElementById(id);
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2});
const num=n=>Number(n||0).toLocaleString('pt-BR');
const pct=n=>(Number(n||0)*100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})+'%';
const css=v=>getComputedStyle(document.body).getPropertyValue(v).trim();
function orderedMonths(rows=rawData){return [...new Set(rows.map(x=>x.mes))].sort((a,b)=>monthsOrder.indexOf(a)-monthsOrder.indexOf(b));}
function fillFilters(){const m=orderedMonths(),s=[...new Set(rawData.map(x=>x.vendedor))].sort();$('monthFilter').innerHTML='<option value="TODOS">Todos os meses</option>'+m.map(x=>`<option>${x}</option>`).join('');$('sellerFilter').innerHTML='<option value="TODOS">Todos</option>'+s.map(x=>`<option>${x}</option>`).join('');const last=m.at(-1),lastRow=rawData.find(x=>x.mes===last);$('generalGoalInput').value=lastRow?.metaGeral||0;}
function currentRows(){const m=$('monthFilter').value,s=$('sellerFilter').value;return rawData.filter(x=>(m==='TODOS'||x.mes===m)&&(s==='TODOS'||x.vendedor===s));}
function sum(rows){return rows.reduce((a,x)=>({orcamentos:a.orcamentos+x.orcamentos,vendas:a.vendas+x.vendas,faturamento:a.faturamento+x.faturamento}),{orcamentos:0,vendas:0,faturamento:0});}
function group(rows,key){const out={};rows.forEach(x=>{const k=x[key];out[k]??={label:k,orcamentos:0,vendas:0,faturamento:0,metaIndividual:0,metaGeral:0,registros:0};out[k].orcamentos+=x.orcamentos;out[k].vendas+=x.vendas;out[k].faturamento+=x.faturamento;out[k].metaIndividual+=x.metaIndividual||0;out[k].metaGeral=Math.max(out[k].metaGeral,x.metaGeral||0);out[k].registros++;});return Object.values(out).map(x=>({...x,conversao:x.vendas/(x.vendas+x.orcamentos)||0,ticket:x.faturamento/x.vendas||0}));}
function prevForSelected(){const selected=$('monthFilter').value;if(selected==='TODOS')return null;const idx=monthsOrder.indexOf(selected);if(idx<=0)return null;const seller=$('sellerFilter').value;return sum(rawData.filter(x=>x.mes===monthsOrder[idx-1]&&(seller==='TODOS'||x.vendedor===seller)));}
function trend(current,previous,pp=false){if(!previous&&previous!==0)return {text:'Selecione um mês para comparar',cls:''};const d=pp?current-previous:(previous?((current-previous)/previous):0);return {text:`${d>=0?'↑':'↓'} ${Math.abs(d*(pp?100:100)).toFixed(2)}${pp?' p.p.':'%'} vs período anterior`,cls:d>=0?'up':'down'};}
function chartBase(){return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:css('--muted'),usePointStyle:true,boxWidth:8,font:{size:10}}}},scales:{x:{ticks:{color:css('--muted'),font:{size:9}},grid:{display:false}},y:{ticks:{color:css('--muted'),font:{size:9}},grid:{color:css('--border')}}}};}
function kill(name){charts[name]?.destroy();}
function render(){const rows=currentRows(),total=sum(rows),months=group(rows,'mes').sort((a,b)=>monthsOrder.indexOf(a.label)-monthsOrder.indexOf(b.label)),sellers=group(rows,'vendedor').sort((a,b)=>b.faturamento-a.faturamento),generalGoal=Number($('generalGoalInput').value)||Math.max(...rows.map(x=>x.metaGeral||0),0),monthCount=Math.max(new Set(rows.map(x=>x.mes)).size,1),effectiveGoal=$('monthFilter').value==='TODOS'?generalGoal*monthCount:generalGoal,conversion=total.vendas/(total.vendas+total.orcamentos)||0,ticket=total.faturamento/total.vendas||0,attainment=effectiveGoal?total.faturamento/effectiveGoal:0,prev=prevForSelected(),prevConv=prev?prev.vendas/(prev.vendas+prev.orcamentos)||0:null;
$('kpiRevenue').textContent=brl(total.faturamento);$('kpiQuotes').textContent=num(total.orcamentos);$('kpiSales').textContent=num(total.vendas);$('kpiConversion').textContent=pct(conversion);$('kpiTicket').textContent=brl(ticket);$('kpiAttainment').textContent=pct(attainment);$('kpiAttainmentText').textContent=attainment>=1?'Meta atingida':'Em andamento';
const revT=trend(total.faturamento,prev?.faturamento),quoteT=trend(total.orcamentos,prev?.orcamentos),saleT=trend(total.vendas,prev?.vendas),convT=trend(conversion,prevConv,true);[['kpiRevenueTrend',revT],['kpiQuotesTrend',quoteT],['kpiSalesTrend',saleT],['kpiConversionTrend',convT]].forEach(([id,t])=>{$(id).textContent=t.text;$(id).className=t.cls});
$('sidebarGoal').textContent=brl(effectiveGoal);$('sidebarAttainment').textContent=pct(attainment);$('sidebarProgress').style.width=Math.min(attainment*100,100)+'%';$('sidebarRealized').textContent=brl(total.faturamento);$('sidebarGap').textContent=brl(Math.max(effectiveGoal-total.faturamento,0));$('updatedAt').textContent=new Date().toLocaleString('pt-BR');
renderCharts(months,sellers,total,effectiveGoal,conversion,attainment);renderRanking(sellers);renderDetails(sellers);renderFunnel(total,conversion);renderInsights(sellers,total,effectiveGoal,conversion,months);}
function renderCharts(months,sellers,total,effectiveGoal,conversion,attainment){const orange=css('--orange'),green=css('--green'),blue=css('--blue'),muted=css('--muted');kill('goalDonut');charts.goalDonut=new Chart($('goalDonut'),{type:'doughnut',data:{datasets:[{data:[Math.min(attainment,1),Math.max(1-attainment,0)],backgroundColor:[green,'#e8edf2'],borderWidth:0}]},options:{responsive:false,cutout:'72%',plugins:{legend:{display:false},tooltip:{enabled:false}}}});
const labels=months.map(x=>x.label);const goals=months.map(x=>x.metaGeral||Number($('generalGoalInput').value)||0);kill('revenueLine');charts.revenueLine=new Chart($('revenueLine'),{type:'line',data:{labels,datasets:[{label:'Faturamento',data:months.map(x=>x.faturamento),borderColor:blue,backgroundColor:'rgba(22,119,255,.10)',fill:false,tension:.35,pointRadius:3},{label:'Meta',data:goals,borderColor:orange,borderDash:[6,5],pointRadius:2}]},options:{...chartBase(),scales:{...chartBase().scales,y:{...chartBase().scales.y,ticks:{callback:v=>'R$ '+Math.round(v/1000)+' mil'}}}}});kill('revenueGoal');charts.revenueGoal=new Chart($('revenueGoal'),{type:'bar',data:{labels,datasets:[{label:'Faturamento',data:months.map(x=>x.faturamento),backgroundColor:blue,borderRadius:3},{label:'Meta',data:goals,backgroundColor:orange,borderRadius:3}]},options:{...chartBase(),scales:{...chartBase().scales,y:{...chartBase().scales.y,ticks:{callback:v=>'R$ '+Math.round(v/1000)+' mil'}}}}});kill('conversionLine');charts.conversionLine=new Chart($('conversionLine'),{type:'line',data:{labels,datasets:[{label:'Conversão',data:months.map(x=>x.conversao*100),borderColor:blue,backgroundColor:blue,tension:.35,pointRadius:3},{label:'Meta',data:months.map(()=>50),borderColor:orange,borderDash:[6,5],pointRadius:2}]},options:{...chartBase(),scales:{...chartBase().scales,y:{...chartBase().scales.y,min:0,max:100,ticks:{callback:v=>v+'%'}}}}});kill('sellerGoal');charts.sellerGoal=new Chart($('sellerGoalChart'),{type:'bar',data:{labels:sellers.map(x=>x.label),datasets:[{label:'Atingimento',data:sellers.map(x=>(x.metaIndividual?x.faturamento/x.metaIndividual:0)*100),backgroundColor:sellers.map(x=>x.faturamento/x.metaIndividual>=1?green:(x.faturamento/x.metaIndividual>=.8?orange:'#e5484d')),borderRadius:4}]},options:{...chartBase(),indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{...chartBase().scales.x,max:150,ticks:{callback:v=>v+'%'}},y:{...chartBase().scales.y}}}});}
function statusClass(v){return v>=1?'good':v>=.8?'warn':'bad';}
function renderRanking(sellers){$('rankingBody').innerHTML=sellers.map((x,i)=>{const a=x.metaIndividual?x.faturamento/x.metaIndividual:0;return `<tr><td>${i+1}</td><td><strong>${x.label}</strong></td><td>${brl(x.faturamento)}</td><td>${brl(x.metaIndividual)}</td><td class="${statusClass(a)}">${pct(a)}</td></tr>`}).join('');}
function sellerPrevious(seller){const selected=$('monthFilter').value;if(selected==='TODOS')return null;const idx=monthsOrder.indexOf(selected);if(idx<=0)return null;return sum(rawData.filter(x=>x.mes===monthsOrder[idx-1]&&x.vendedor===seller));}
function renderDetails(sellers){$('detailsBody').innerHTML=sellers.map(x=>{const a=x.metaIndividual?x.faturamento/x.metaIndividual:0,p=sellerPrevious(x.label),delta=p&&p.faturamento?(x.faturamento-p.faturamento)/p.faturamento:null;return `<tr><td><strong>${x.label}</strong></td><td>${num(x.orcamentos)}</td><td>${num(x.vendas)}</td><td>${pct(x.conversao)}</td><td>${brl(x.faturamento)}</td><td>${brl(x.ticket)}</td><td>${brl(x.metaIndividual)}</td><td class="${statusClass(a)}">${pct(a)}</td><td class="${delta===null?'':delta>=0?'good':'bad'}">${delta===null?'—':`${delta>=0?'↑':'↓'} ${Math.abs(delta*100).toFixed(2)}%`}</td></tr>`}).join('');}
function renderFunnel(total,conversion){const opp=total.orcamentos+total.vendas,proposal=Math.round((opp+total.vendas)/2),rows=[['Orçamentos',opp,'#0878e8'],['Propostas',proposal,'#2eae55'],['Vendas',total.vendas,'#ff8b00'],['Conversão',pct(conversion),'#e53935']];$('funnel').innerHTML=rows.map((x,i)=>`<div class="funnel-row" style="width:${100-i*12}%;background:${x[2]}"><div><small>${x[0]}</small>${typeof x[1]==='number'?num(x[1]):x[1]}</div></div>`).join('');}
function renderInsights(sellers,total,goal,conversion,months){const best=sellers[0],efficient=[...sellers].sort((a,b)=>b.conversao-a.conversao)[0],below=sellers.filter(x=>x.faturamento<x.metaIndividual).map(x=>x.label),latest=months.at(-1),prev=months.at(-2),growth=prev&&prev.faturamento?(latest.faturamento-prev.faturamento)/prev.faturamento:0;const cards=[`O faturamento atingiu <strong>${pct(total.faturamento/goal||0)}</strong> da meta geral.`,`${best?.label||'—'} lidera o faturamento com <strong>${brl(best?.faturamento||0)}</strong>.`,`${efficient?.label||'—'} possui a maior conversão: <strong>${pct(efficient?.conversao||0)}</strong>.`,below.length?`Atenção às metas de <strong>${below.join(', ')}</strong>.`:`Todos os vendedores atingiram suas metas.`];$('insightCards').innerHTML=cards.map(x=>`<div class="insight-card">${x}</div>`).join('');}
function parseWorkbook(file){const reader=new FileReader();reader.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'});let out=[];const normalized=wb.Sheets['DADOS DASHBOARD'];if(normalized){const rows=XLSX.utils.sheet_to_json(normalized,{defval:null});out=rows.map(r=>({mes:String(r['MÊS']||'').toUpperCase(),vendedor:String(r['VENDEDOR']||''),orcamentos:Number(r['ORÇAMENTOS']),vendas:Number(r['VENDAS']),faturamento:Number(r['FATURAMENTO']),metaIndividual:Number(r['META INDIVIDUAL']),metaGeral:Number(r['META GERAL'])})).filter(x=>x.mes&&x.vendedor&&Number.isFinite(x.faturamento));}else{const ws=wb.Sheets[wb.SheetNames[0]],grid=XLSX.utils.sheet_to_json(ws,{header:1,raw:true}),metasSheet=wb.Sheets['METAS'],metaRows=metasSheet?XLSX.utils.sheet_to_json(metasSheet,{defval:0}):[],metaMap={};metaRows.forEach(r=>{const m=String(r['MÊS']||'').toUpperCase();metaMap[m]=r;});for(let r=0;r<grid.length;r++){const month=String(grid[r]?.[0]||'').trim().toUpperCase();if(!month)continue;for(let c=1;c<grid[r].length;c+=2){const seller=String(grid[r]?.[c]||'').trim();if(!seller)continue;const o=Number(grid[r+1]?.[c+1]),v=Number(grid[r+2]?.[c+1]),f=Number(grid[r+4]?.[c+1]);if(Number.isFinite(o)&&Number.isFinite(v)&&Number.isFinite(f)){const mr=metaMap[month]||{};out.push({mes:month,vendedor:seller[0].toUpperCase()+seller.slice(1).toLowerCase(),orcamentos:o,vendas:v,faturamento:f,metaIndividual:Number(mr[seller.toUpperCase()]||0),metaGeral:Number(mr['META GERAL']||0)});}}}}if(!out.length)throw new Error('Formato não reconhecido');rawData=out;fillFilters();render();alert('Planilha importada com sucesso.');}catch(err){console.error(err);alert('Não foi possível ler a planilha. Use o modelo incluído na pasta dados.');}};reader.readAsArrayBuffer(file);}
function exportCSV(){const rows=currentRows(),head='Mês;Vendedor;Orçamentos;Vendas;Conversão;Faturamento;Meta Individual;Meta Geral\n',body=rows.map(x=>[x.mes,x.vendedor,x.orcamentos,x.vendas,((x.vendas/(x.vendas+x.orcamentos)||0)*100).toFixed(2),x.faturamento.toFixed(2),x.metaIndividual.toFixed(2),x.metaGeral.toFixed(2)].join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+head+body],{type:'text/csv'}));a.download='dashboard_eletrica_lima.csv';a.click();}
$('monthFilter').onchange=render;$('sellerFilter').onchange=render;$('generalGoalInput').oninput=render;$('excelInput').onchange=e=>e.target.files[0]&&parseWorkbook(e.target.files[0]);$('refreshBtn').onclick=render;$('printBtn').onclick=()=>print();$('csvBtn').onclick=exportCSV;$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');render()};fillFilters();render();
