let rawData=[...window.INITIAL_DATA];let charts={};
const monthOrder=['JANEIRO','FEVEREIRO','MARÇO','ABRIL','MAIO','JUNHO','JULHO','AGOSTO','SETEMBRO','OUTUBRO','NOVEMBRO','DEZEMBRO'];
const colors=['#246bfd','#7a4af6','#16a36a','#f1a22b','#09a8c4','#d64b5f'];
const $=id=>document.getElementById(id);
const brl=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const num=n=>Number(n||0).toLocaleString('pt-BR');
const pct=n=>(Number(n||0)*100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})+'%';
const target=()=>Number($('targetInput').value)||0;
function options(){const months=[...new Set(rawData.map(d=>d.mes))].sort((a,b)=>monthOrder.indexOf(a)-monthOrder.indexOf(b));const sellers=[...new Set(rawData.map(d=>d.vendedor))].sort();$('monthFilter').innerHTML='<option value="TODOS">Todos os meses</option>'+months.map(x=>`<option>${x}</option>`).join('');$('sellerFilter').innerHTML='<option value="TODOS">Todos os vendedores</option>'+sellers.map(x=>`<option>${x}</option>`).join('')}
function filtered(){const m=$('monthFilter').value,v=$('sellerFilter').value;return rawData.filter(d=>(m==='TODOS'||d.mes===m)&&(v==='TODOS'||d.vendedor===v))}
function aggregate(rows,key){const map={};rows.forEach(d=>{const k=d[key];map[k]??={label:k,orcamentos:0,vendas:0,faturamento:0};map[k].orcamentos+=d.orcamentos;map[k].vendas+=d.vendas;map[k].faturamento+=d.faturamento});return Object.values(map).map(x=>({...x,conversao:x.vendas/(x.vendas+x.orcamentos)||0,ticket:x.faturamento/x.vendas||0}))}
function totals(rows){return rows.reduce((a,d)=>({orcamentos:a.orcamentos+d.orcamentos,vendas:a.vendas+d.vendas,faturamento:a.faturamento+d.faturamento}),{orcamentos:0,vendas:0,faturamento:0})}
function destroy(name){if(charts[name])charts[name].destroy()}
function baseChart(){const css=getComputedStyle(document.body),muted=css.getPropertyValue('--muted'),border=css.getPropertyValue('--border');return{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:muted,boxWidth:10,usePointStyle:true}}},scales:{x:{ticks:{color:muted},grid:{display:false}},y:{ticks:{color:muted},grid:{color:border}}}}}
function previousMonth(rows){const selected=$('monthFilter').value;if(selected==='TODOS')return null;const idx=monthOrder.indexOf(selected);if(idx<=0)return null;const prev=monthOrder[idx-1];return totals(rawData.filter(d=>d.mes===prev&&($('sellerFilter').value==='TODOS'||d.vendedor===$('sellerFilter').value)))}
function trendText(current,previous,kind='money'){if(!previous)return 'Selecione um mês para comparar';const delta=previous===0?0:(current-previous)/previous;const arrow=delta>=0?'▲':'▼';return `${arrow} ${Math.abs(delta*100).toFixed(1)}% vs. mês anterior`}
function render(){const rows=filtered();const total=totals(rows);total.conversao=total.vendas/(total.vendas+total.orcamentos)||0;total.ticket=total.faturamento/total.vendas||0;const sellers=aggregate(rows,'vendedor').sort((a,b)=>b.faturamento-a.faturamento);const months=aggregate(rows,'mes').sort((a,b)=>monthOrder.indexOf(a.label)-monthOrder.indexOf(b.label));const prev=previousMonth(rows);const meta=target();const sellerCount=Math.max(sellers.length,1);const metaTotal=meta*sellerCount*Math.max(new Set(rows.map(d=>d.mes)).size,1);const attainment=metaTotal?total.faturamento/metaTotal:0;
$('kpiRevenue').textContent=brl(total.faturamento);$('kpiConversion').textContent=pct(total.conversao);$('kpiSales').textContent=num(total.vendas);$('kpiQuotes').textContent=num(total.orcamentos);$('kpiTicket').textContent='Ticket médio '+brl(total.ticket);$('kpiLeader').textContent=sellers[0]?.label||'—';$('kpiLeaderValue').textContent=sellers[0]?brl(sellers[0].faturamento):'—';$('kpiTarget').textContent=pct(attainment);$('kpiTargetText').textContent='Meta considerada '+brl(meta)+' / vendedor / mês';$('scoreValue').textContent=pct(total.conversao);
const revTrend=$('kpiRevenueTrend'),convTrend=$('kpiConversionTrend');revTrend.textContent=trendText(total.faturamento,prev?.faturamento);const prevConv=prev?prev.vendas/(prev.vendas+prev.orcamentos)||0:null;convTrend.textContent=prev?`${(total.conversao-prevConv)>=0?'▲':'▼'} ${Math.abs((total.conversao-prevConv)*100).toFixed(1)} p.p. vs. mês anterior`:'Selecione um mês para comparar';revTrend.className=prev&&total.faturamento<prev.faturamento?'trend-down':'trend-up';convTrend.className=prev&&total.conversao<prevConv?'trend-down':'trend-up';
const convLeader=[...sellers].sort((a,b)=>b.conversao-a.conversao)[0],growth=months.length>1?(months.at(-1).faturamento-months.at(-2).faturamento)/months.at(-2).faturamento:0;$('insightTitle').textContent=convLeader?`${convLeader.label} lidera em eficiência comercial`:'Sem dados';$('insightText').textContent=convLeader?`Conversão de ${pct(convLeader.conversao)}. ${sellers[0].label} lidera o faturamento com ${brl(sellers[0].faturamento)}. A variação mais recente do faturamento consolidado foi de ${(growth*100).toFixed(1)}%.`:'Importe uma planilha válida.';
chartsRender(months,sellers);tableRender(rows);funnelRender(total);goalsRender(sellers,meta);$('statusText').textContent=`${rows.length} registros analisados`}
function chartsRender(months,sellers){destroy('trend');charts.trend=new Chart($('trendChart'),{type:'bar',data:{labels:months.map(x=>x.label),datasets:[{type:'bar',label:'Faturamento',data:months.map(x=>x.faturamento),backgroundColor:'rgba(36,107,253,.72)',yAxisID:'y'},{type:'line',label:'Conversão',data:months.map(x=>x.conversao*100),borderColor:'#16a36a',backgroundColor:'#16a36a',tension:.35,pointRadius:4,yAxisID:'y1'}]},options:{...baseChart(),scales:{x:baseChart().scales.x,y:{...baseChart().scales.y,ticks:{callback:v=>'R$ '+(v/1000).toFixed(0)+' mil'}},y1:{position:'right',beginAtZero:true,max:100,grid:{drawOnChartArea:false},ticks:{callback:v=>v+'%'}}}}});
destroy('ranking');charts.ranking=new Chart($('rankingChart'),{type:'doughnut',data:{labels:sellers.map(x=>x.label),datasets:[{data:sellers.map(x=>x.faturamento),backgroundColor:colors,borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'62%',plugins:{legend:{position:'bottom',labels:{color:getComputedStyle(document.body).getPropertyValue('--muted'),usePointStyle:true}}}}});
destroy('conversion');charts.conversion=new Chart($('conversionChart'),{type:'bar',data:{labels:sellers.map(x=>x.label),datasets:[{label:'Conversão',data:sellers.map(x=>x.conversao*100),backgroundColor:colors}]},options:{...baseChart(),plugins:{legend:{display:false}},scales:{...baseChart().scales,y:{...baseChart().scales.y,beginAtZero:true,max:100,ticks:{callback:v=>v+'%'}}}}});
destroy('volume');charts.volume=new Chart($('volumeChart'),{type:'bar',data:{labels:sellers.map(x=>x.label),datasets:[{label:'Orçamentos',data:sellers.map(x=>x.orcamentos),backgroundColor:'#a8b2c7'},{label:'Vendas',data:sellers.map(x=>x.vendas),backgroundColor:'#246bfd'}]},options:baseChart()});
destroy('scatter');charts.scatter=new Chart($('scatterChart'),{type:'bubble',data:{datasets:sellers.map((x,i)=>({label:x.label,data:[{x:x.conversao*100,y:x.faturamento,r:Math.max(7,Math.min(24,x.vendas/15))}],backgroundColor:colors[i%colors.length]}))},options:{...baseChart(),scales:{x:{...baseChart().scales.x,title:{display:true,text:'Conversão (%)'},min:0,max:100},y:{...baseChart().scales.y,title:{display:true,text:'Faturamento'},ticks:{callback:v=>'R$ '+(v/1000).toFixed(0)+' mil'}}}}})}
function goalsRender(sellers,meta){$('goalBars').innerHTML=sellers.map(x=>{const rate=meta?x.faturamento/meta:0;return `<div class="goal-row"><strong>${x.label}</strong><div class="goal-track"><div class="goal-fill" style="width:${Math.min(rate*100,100)}%"></div></div><span class="${rate>=1?'meta-ok':'meta-low'}">${pct(rate)}</span></div>`}).join('')}
function funnelRender(t){const opp=t.orcamentos+t.vendas;const levels=[['Oportunidades',opp,'100%','#246bfd'],['Vendas',t.vendas,pct(t.vendas/opp||0),'#4d84f7'],['Faturamento',brl(t.faturamento),'Ticket '+brl(t.faturamento/t.vendas||0),'#16a36a']];$('funnel').innerHTML=levels.map((x,i)=>`<div class="funnel-row" style="width:${100-i*15}%;background:${x[3]}"><span>${x[0]}</span><span>${typeof x[1]==='number'?num(x[1]):x[1]} <small>${x[2]}</small></span></div>`).join('')}
function tableRender(rows){const q=$('searchInput').value.toLowerCase(),meta=target();$('dataBody').innerHTML=rows.filter(d=>(d.vendedor+' '+d.mes).toLowerCase().includes(q)).map(d=>{const rate=meta?d.faturamento/meta:0;return `<tr><td><strong>${d.vendedor}</strong></td><td>${d.mes}</td><td>${num(d.orcamentos)}</td><td>${num(d.vendas)}</td><td><span class="badge">${pct(d.vendas/(d.vendas+d.orcamentos)||0)}</span></td><td>${brl(d.faturamento)}</td><td>${brl(d.faturamento/d.vendas||0)}</td><td class="${rate>=1?'meta-ok':'meta-low'}">${pct(rate)}</td></tr>`}).join('')}
function parseExcel(file){const reader=new FileReader();reader.onload=e=>{const wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],grid=XLSX.utils.sheet_to_json(ws,{header:1,raw:true});const out=[];for(let r=0;r<grid.length;r++){const month=String(grid[r]?.[0]||'').trim().toUpperCase();if(!month)continue;for(let c=1;c<grid[r].length;c+=2){const seller=String(grid[r]?.[c]||'').trim();if(!seller)continue;const o=Number(grid[r+1]?.[c+1]),v=Number(grid[r+2]?.[c+1]),f=Number(grid[r+4]?.[c+1]);if(Number.isFinite(o)&&Number.isFinite(v)&&Number.isFinite(f))out.push({mes:month,vendedor:seller[0].toUpperCase()+seller.slice(1).toLowerCase(),orcamentos:o,vendas:v,faturamento:f,conversao:v/(o+v)});}}if(out.length){rawData=out;options();render();alert('Planilha importada com sucesso.')}else alert('Não foi possível reconhecer o formato da planilha.');};reader.readAsArrayBuffer(file)}
function exportCSV(){const rows=filtered(),meta=target(),head='Mês;Vendedor;Orçamentos;Vendas;Conversão;Faturamento;Ticket Médio;Atingimento Meta\n',body=rows.map(d=>[d.mes,d.vendedor,d.orcamentos,d.vendas,((d.vendas/(d.vendas+d.orcamentos)||0)*100).toFixed(2),d.faturamento.toFixed(2),(d.faturamento/d.vendas||0).toFixed(2),meta?(d.faturamento/meta*100).toFixed(2):0].join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+head+body],{type:'text/csv'}));a.download='dashboard_comercial_v2.csv';a.click()}
$('monthFilter').onchange=render;$('sellerFilter').onchange=render;$('targetInput').oninput=render;$('searchInput').oninput=()=>tableRender(filtered());$('resetBtn').onclick=()=>{$('monthFilter').value='TODOS';$('sellerFilter').value='TODOS';$('searchInput').value='';$('targetInput').value=500000;render()};$('printBtn').onclick=()=>print();$('csvBtn').onclick=exportCSV;$('excelInput').onchange=e=>e.target.files[0]&&parseExcel(e.target.files[0]);$('themeBtn').onclick=()=>{document.body.classList.toggle('dark');render()};options();render();